name: Rust

on:
    push:
        tags: ["*"]

env:
    CARGO_TERM_COLOR: always

jobs:
    release:
        runs-on: windows-latest
        steps:
            - uses: actions/checkout@v4
            - name: Build
              run: cargo build --verbose --release
            - uses: actions/checkout@v4
            - uses: softprops/action-gh-release@v2
              with:
                  files: target/release/ufbr.exe
